if Env.IS_DEBUG
	Config =
		PARSE_APPLICATION_ID: 'j7jHjBZmBoBgcCkyOtNFSRF1xDyiceCG4ydubBpY'
		PARSE_JAVASCRIPT_KEY: 'VaTmBubBco2b00gohLgtyhSaGOCiCe8OpARaO1jh'
		# FACEBOOK_APP_ID: '<FACEBOOK_APP_ID_DEV>'
else
	Config =
		PARSE_APPLICATION_ID: 'PhXmIIWMq0LidSBxrScY3cbeFTazffBp026qTuH6'
		PARSE_JAVASCRIPT_KEY: 'Z814JI5WCZtgMrtGsKUMq5NOeEfhueQgNpDUayYp'
		# FACEBOOK_APP_ID: '<FACEBOOK_APP_ID_DEV>'
