if Env.IS_DEBUG
	Config =
		PARSE_APPLICATION_ID: '<PARSE_APPLICATION_ID_DEV>'
		PARSE_REST_API_KEY: '<PARSE_REST_API_KEY_DEV>'
		# FACEBOOK_APP_ID: '<FACEBOOK_APP_ID_DEV>'
else
	Config =
		PARSE_APPLICATION_ID: '<PARSE_APPLICATION_ID>'
		PARSE_REST_API_KEY: '<PARSE_REST_API_KEY>'
		# FACEBOOK_APP_ID: '<FACEBOOK_APP_ID_DEV>'
