if Env.IS_DEBUG
	Config =
		PARSE_APPLICATION_ID: '<PARSE_APPLICATION_ID_DEV>'
		PARSE_JAVASCRIPT_KEY: '<PARSE_JAVASCRIPT_KEY>'
		# FACEBOOK_APP_ID: '<FACEBOOK_APP_ID_DEV>'
else
	Config =
		PARSE_APPLICATION_ID: '<PARSE_APPLICATION_ID>'
		PARSE_JAVASCRIPT_KEY: '<PARSE_JAVASCRIPT_KEY>'
		# FACEBOOK_APP_ID: '<FACEBOOK_APP_ID_DEV>'
